In [1]:
import numpy as np
import pandas as pd
#from pandas_datareader import data as wb
import matplotlib.pyplot as plt

In [11]:
import yfinance as yf
Data = pd.DataFrame()
#define the ticker symbol
tickerSymbol =[ "XAUUSD"]#, "CL=F"] # "GOLD"
n=0
for t in tickerSymbol:
    #get data on this ticker
    tickerData = yf.Ticker(tickerSymbol[n])
    #get the historical prices for this ticker
    Data[t] = tickerData.history(interval='1mo', start='2015-01-01', end='2022-05-01')['Close']
    n=n+1
Data

- XAUUSD: No data found, symbol may be delisted

Empty DataFrame
Columns: [XAUUSD]
Index: []

In [8]:
Data.to_csv("Gold-XAU.csv")

In [2]:
pip install yfinance

Note: you may need to restart the kernel to use updated packages.

  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000027384B88C40>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/a1/b5/bf3bf6adf9acdd18ac15f93e2d42b7a9a468f8cb70144e316980d9d9dd61/yfinance-0.1.70-py2.py3-none-any.whl

Collecting yfinance
  Downloading yfinance-0.1.70-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: pandas>=0.24.0 in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from yfinance) (1.3.2)
Requirement already satisfied: requests>=2.26 in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from yfinance) (2.26.0)
Requirement already satisfied: numpy>=1.15 in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from yfinance) (1.21.0)
Collecting lxml>=4.5.1
  Downloading lxml-4.8.0-cp39-cp39-win_amd64.whl (3.6 MB)
     ---------------------------------------- 3.6/3.6 MB 511.4 kB/s eta 0:00:00
Collecting multitasking>=0.0.7
  Downloading multitasking-0.0.10.tar.gz (8.2 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: pytz>=2017.3 in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from pandas>=0.24.0->yfinance) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from pandas>=0.24.0->yfinance) (2.8.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.26->yfinance) (2021.5.30)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.26->yfinance) (3.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.26->yfinance) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.26->yfinance) (1.26.6)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yfinance) (1.16.0)
Using legacy 'setup.py install' for multitasking, since package 'wheel' is not installed.
Installing collected packages: multitasking, lxml, yfinance
  Running setup.py install for multitasking: started
  Running setup.py install for multitasking: finished with status 'done'
Successfully installed lxml-4.8.0 multitasking-0.0.10 yfinance-0.1.70

WARNING: You are using pip version 22.0.1; however, version 22.1 is available.
You should consider upgrading via the 'c:\Users\LENOVO\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [15]:
import yfinance as yf
Data = pd.DataFrame()
#define the ticker symbol
tickerSymbol =["BTC-USD" , "ETH-USD" , "XRP-USD" , "SOL-USD" , "LUNA1-USD" , "ADA-USD" , "AVAX-USD" , "DOT-USD" , "DOGE-USD" , "MATIC-USD"]
#tickerSymbol = ['X', 'CLF', 'ABEV', 'KGC']
n=0
for t in tickerSymbol:
    #get data on this ticker
    tickerData = yf.Ticker(tickerSymbol[n])
    #get the historical prices for this ticker
    Data[t] = tickerData.history(period='1d', start='2021-01-01', end='2022-01-01')['Close']
    n=n+1
Data
#Data.to_csv("Data_crypto.csv")

,BTC-USD,ETH-USD,XRP-USD,SOL-USD,LUNA1-USD,ADA-USD,AVAX-USD,DOT-USD,DOGE-USD,MATIC-USD
Date,,,,,,,,,,
2020-12-31,29001.720703,737.803406,0.219846,1.510898,0.652520,0.181397,3.135609,9.292508,0.004682,0.017633
2021-01-01,29374.152344,730.367554,0.237444,1.842084,0.649443,0.175350,3.664823,8.306819,0.005685,0.017812
2021-01-02,32127.267578,774.534973,0.221655,1.799275,0.631426,0.177423,3.494940,9.208837,0.010615,0.019043
2021-01-03,32782.023438,975.507690,0.225848,2.161752,0.661895,0.204995,3.472944,10.033283,0.009771,0.019975
2021-01-04,31971.914062,1040.233032,0.236677,2.485097,0.670244,0.224762,3.590243,9.469611,0.009767,0.024614
...,...,...,...,...,...,...,...,...,...,...
2021-12-27,50640.417969,4037.547607,0.926184,195.429504,90.800499,1.512913,113.598618,30.908672,0.187705,2.725954
2021-12-28,47588.855469,3800.893066,0.852960,177.425629,85.368347,1.402264,107.215614,27.907103,0.174117,2.498206
2021-12-29,46444.710938,3628.531738,0.816714,170.657562,84.059334,1.330814,102.998123,26.744373,0.167765,2.470006
2021-12-30,47178.125000,3713.852051,0.839649,172.751190,84.711868,1.360415,101.928276,27.567789,0.171313,2.557751
2021-12-31,46306.445312,3682.632812,0.831163,170.299072,85.472542,1.310209,109.270485,26.719675,0.170496,2.527107

In [16]:
Data.to_csv("Data_crypto.csv")

In [24]:
#6 mounths
import yfinance as yf
Data6 = pd.DataFrame()
#define the ticker symbol
tickerSymbol =["BTC-USD" , "ETH-USD" , "XRP-USD" , "SOL-USD" , "LUNA1-USD" , "ADA-USD" , "AVAX-USD" , "DOT-USD" , "DOGE-USD" , "MATIC-USD"]
#tickerSymbol = ['X', 'CLF', 'ABEV', 'KGC']
n=0
for t in tickerSymbol:
    #get data on this ticker
    tickerData = yf.Ticker(tickerSymbol[n])
    #get the historical prices for this ticker
    Data6[t] = tickerData.history(period='1d', start='2021-11-01', end='2022-05-01')['Close']
    n=n+1
Data6

,BTC-USD,ETH-USD,XRP-USD,SOL-USD,LUNA1-USD,ADA-USD,AVAX-USD,DOT-USD,DOGE-USD,MATIC-USD
Date,,,,,,,,,,
2021-10-31,61318.957031,4288.074219,1.113247,202.421021,42.889774,1.965026,64.287804,42.742096,0.280244,1.935003
2021-11-01,61004.406250,4324.626953,1.092867,203.545090,44.059307,1.950002,65.072517,49.982254,0.271728,1.903897
2021-11-02,63226.402344,4584.798828,1.136196,220.239594,44.755489,1.971377,67.584557,51.631351,0.273121,1.937505
2021-11-03,62970.046875,4607.193848,1.208796,242.898819,48.061790,2.063701,75.430420,53.443703,0.269407,2.034598
2021-11-04,61452.230469,4537.324219,1.202003,247.387772,51.922386,1.984882,79.293221,53.881733,0.263280,1.917041
...,...,...,...,...,...,...,...,...,...,...
2022-04-26,38117.460938,2808.298340,0.641699,95.782150,88.550468,0.827645,68.672058,NaN,0.137767,1.242833
2022-04-27,39241.121094,2888.929688,0.652318,98.378868,89.090111,0.840595,69.857727,16.948017,0.139700,1.257685
2022-04-28,39773.828125,2936.940918,0.644363,98.185730,88.961685,0.843950,67.319450,16.996513,0.137363,1.238904
2022-04-29,38609.824219,2815.601807,0.611407,94.011345,85.116302,0.805043,63.417095,16.162790,0.135027,1.140579
2022-04-30,37714.875000,2730.186768,0.587091,85.095932,78.344093,0.756660,57.048004,14.519939,0.127557,1.035750

In [25]:
Data6.to_csv("Data_crypto_6_month.csv")

In [26]:
import yfinance as yf
Dataq3 = pd.DataFrame()
#define the ticker symbol
tickerSymbol =["BTC-USD" , "ETH-USD" , "XRP-USD"]
#tickerSymbol = ['X', 'CLF', 'ABEV', 'KGC']
n=0
for t in tickerSymbol:
    #get data on this ticker
    tickerData = yf.Ticker(tickerSymbol[n])
    #get the historical prices for this ticker
    Dataq3[t] = tickerData.history(period='1d', start='2021-01-01', end='2022-01-01')['Close']
    n=n+1
Dataq3

                 BTC-USD      ETH-USD   XRP-USD
Date
2020-12-31  29001.720703   737.803406  0.219846
2021-01-01  29374.152344   730.367554  0.237444
2021-01-02  32127.267578   774.534973  0.221655
2021-01-03  32782.023438   975.507690  0.225848
2021-01-04  31971.914062  1040.233032  0.236677
...                  ...          ...       ...
2021-12-27  50640.417969  4037.547607  0.926184
2021-12-28  47588.855469  3800.893066  0.852960
2021-12-29  46444.710938  3628.531738  0.816714
2021-12-30  47178.125000  3713.852051  0.839649
2021-12-31  46306.445312  3682.632812  0.831163

[366 rows x 3 columns]

In [ ]:
Dataq3.to_csv("Data_crypto_q3.csv")

In [1]:
#Bitcoin
import yfinance as yf
Data_bitcoin = pd.DataFrame()
#define the ticker symbol

n=0

tickerData = yf.Ticker("BTC-USD")
#get the historical prices for this ticker
Data_bitcoin["BTC-USD"] = tickerData.history(period='1d', start='2021-05-01', end='2022-05-01')['Close']
n=n+1
Data_bitcoin

NameError: name 'pd' is not defined

In [10]:
Data_bitcoin.to_csv("Data_Bitcoin.csv")

In [14]:
#3 year

import yfinance as yf
Data = pd.DataFrame()
#define the ticker symbol
tickerSymbol =["BTC-USD" , "ETH-USD" , "XRP-USD" , "ADA-USD" , "DOGE-USD"]
#tickerSymbol = ['X', 'CLF', 'ABEV', 'KGC']
n=0
for t in tickerSymbol:
    #get data on this ticker
    tickerData = yf.Ticker(tickerSymbol[n])
    #get the historical prices for this ticker
    Data[t] = tickerData.history(period='1d', start='2019-05-01', end='2022-05-01')['Close']
    n=n+1
Data

                 BTC-USD      ETH-USD   XRP-USD   ADA-USD  DOGE-USD
Date
2019-04-30   5350.726562   162.166031  0.309476  0.070346  0.002513
2019-05-01   5402.697266   160.818344  0.304696  0.069014  0.002521
2019-05-02   5505.283691   162.122787  0.303239  0.068579  0.002611
2019-05-03   5768.289551   167.952408  0.308222  0.069858  0.002721
2019-05-04   5831.167480   164.026581  0.304552  0.066880  0.002680
...                  ...          ...       ...       ...       ...
2022-04-26  38117.460938  2808.298340  0.641699  0.827645  0.137767
2022-04-27  39241.121094  2888.929688  0.652318  0.840595  0.139700
2022-04-28  39773.828125  2936.940918  0.644363  0.843950  0.137363
2022-04-29  38609.824219  2815.601807  0.611407  0.805043  0.135027
2022-04-30  37714.875000  2730.186768  0.587091  0.756660  0.127557

[1097 rows x 5 columns]

In [15]:
Data.to_csv("Data_3_year.csv")